import mimetypes
print(mimetypes.guess_type('datas/csv/handMNIST2828_predict.xlsx'))
# ('application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', None)
print(mimetypes.guess_type('datas/images/book.jpg'))
# ('image/jpeg', None)
print(mimetypes.guess_type('datas/videos/Armbot.mp4'))
# ('video/mp4', None)
print(mimetypes.guess_type('datas/videos/output.avi'))
# ('video/x-msvideo', None)
print(mimetypes.guess_type('datas/haar_cascade_files/haarcascade_eye.xml'))